#!/bin/sh
export LANG=en_US.UTF-8

REPOS="$1"
TXN="$2"
TYPE="$3"
if test -z "$TYPE" ; then
    TYPE="-t"
fi

SVNLOOK=/usr/local/bin/svnlook
CSV=/opt/csv/src

set -e
exec 1>&2

${CSV}/pre-commit.py "$REPOS" "$TXN" || exit 195
${CSV}/pre-commit.sh "$REPOS" "$TXN" "$TYPE" || exit 196

# All checks passed, so allow the commit.
exit 0
